### ISSUE TITLE
consider loading=lazy attribute

### ISSUE THREAD

**Issue by paulirish** [paulirish/lite-youtube-embed#11]
a la https://github.com/GoogleChrome/web.dev/pull/1881/files

Will need some research to understand the semantics here and also the fallback story.

**Comment by Garbee** [comment]
If the initial click of the component makes the iframe and injects it, isn't that by default lazily loading until the user is ready to consume it?

[The attribute](https://web.dev/native-lazy-loading/#the-loading-attribute) is about holding off the load until it is close to the viewport. Since the user can click it, it's in the viewport already. If we want this kind of behavior, then our component should use `IntersectionObserver` (I *think*, could be another observer) to check where it is on the viewport. When it's close to being scrolled in, go ahead and load the iframe up. So we'd essentially polyfill this attribute over our custom element.

**Comment by tpinne** [comment]
Just read about this component a few minutes ago and read a bit across everything.

If you consider "lazy" loading the iframe automatically when it reaches the viewport it would be great if that would be an **opt-in or opt-out** feature. 

As I saw from the demos the current implementation, that the user has to actively click to load the iframe, this component seems to be somehow GDPR compliant (maybe only partially, don't know exactly) because there is no interaction with YouTube whatsoever until that point. Especially if you provide a custom locally stored preview image.

But as this a very big topic (at least here in Germany) it would be great to have a simple component like this in our toolbelt. For performance and GDPR reasons.

**Comment by paulirish** [comment]
The more I learn about `loading=lazy` the more I think it's not a great fit for this project.

IMO it's the superquick hack to make an existing youtube embed a tad better (only only in the few browsers that support this right now).

it helps a lot for embeds that are not in the viewport.
but if there are embeds that load within the viewport but are not always clicked, then the YT download/JS costs still were pretty painful.

so I think we won't be needing this attribute. :)
