### ISSUE TITLE
Make it ES5 compliant

### ISSUE THREAD

**Issue by XhmikosR** [paulirish/lite-youtube-embed#7]

**Comment by spacedawwwg** [comment]
could this not be handled by babel if required?

**Comment by XhmikosR** [comment]
It could, yeah, but we shouldn't make things more complex :)

I mean, if we can do without babel, it'd be better.

**Comment by paulirish** [comment]
it's been a while since i've published web-facing JS... are there any tools I can use to validate my npm package is es5-compliant?

**Comment by XhmikosR** [comment]
There was an ESLint plugin, but I didn't have the best experience when I used it a long time ago. So maybe now it's been improved https://www.npmjs.com/package/stylelint-no-unsupported-browser-features

That being said, since the code isn't much, I can help if you need me. The .browserslistrc approach is the safest one, though, so that we have autoprefixer also if needed later. Although, from a quick look, the CSS is quite simple, so maybe only the JS part needs some love :)

**Comment by XhmikosR** [comment]
Err, I meant https://github.com/amilajack/eslint-plugin-compat

**Comment by XhmikosR** [comment]
Actually, scratch that. I don't think ES5 is needed https://caniuse.com/#feat=custom-elementsv1, right?

In that case, maybe there should be some feature checking?

**Comment by justinfagnani** [comment]
I would not publish custom elements as ES5. Since custom elements extend HTMLElement and _must_ do a proper `super()` constructor call, they can't actually easily be compiled to ES5 class patterns. If you do, you'll need to include something like the custom-elements-es5-adapter from the web components polyfills, which can slow down all custom elements on the page.

It's much better to let consumers compile to old JS if they need to for their browser support requirements.

**Comment by Garbee** [comment]
Yea, ES6 is required to properly publish Web Components. Distributing something older hinders the integration and performance.

Why did you initially request ES5 compatibility? What was the driving context that deemed ES5 a necessity?

**Comment by XhmikosR** [comment]
I hadn't actually read the code :)

**Comment by ahmadalfy** [comment]
> it's been a while since i've published web-facing JS

Welcome back @paulirish 😄
