### ISSUE TITLE
Duplicate Iframe/video player being added

### ISSUE THREAD

**Issue by billyswifty** [paulirish/lite-youtube-embed#92]
After the play button is clicked, the script inserts duplicate <iframe> YouTube players onto the page and plays them both. So I hear duplicate audio tracks, and if I pause the video, the duplicate is still playing in the background. I have tested in multiple browsers. This is the [page](https://junkyardbots2.caboosecms.com/media) I am currently testing on.

<img width="545" alt="Screen Shot 2021-08-05 at 8 11 44 AM" src="https://user-images.githubusercontent.com/1225716/128356072-dbf84b37-2669-410b-bc4b-f2634491c194.png">

```
<head>
  <link rel="stylesheet" href="/lite-youtube-embed/src/lite-yt-embed.css" />
  <script>
    $(document).ready(function() {
        if ( $("#youtube-lite-script").length == 0 ) {
          let yt_script = document.createElement("script");
          yt_script.setAttribute("src", "/assets/lite-yt-embed.js");
          yt_script.setAttribute("id", "youtube-lite-script");
          document.body.appendChild(yt_script);
        }
      });
  </script>
</head>
<div class="iframe-holder">
  <lite-youtube class="fake-video" videoid="EQbxkhkuKsM" params="rel=0&origin=https://junkyardbots2.caboosecms.com" playlabel="Play Video"></lite-youtube>
</div>
```

**Comment by denFete** [comment]
Got the same issue....  @billyswifty Have you solved it somehow?

**Comment by thomasali** [comment]
Getting the same issue, currently adding the following to the start of the `addIframe()` method:

```
addIframe() {
    if(jQuery(this).children('iframe').length > 0) {
        // If there is already an iframe return as we don't want to create another
        return;
	}
	...
```

**Comment by codepuncher** [comment]
I had the same problem. For me, it was caused by https://github.com/paulirish/lite-youtube-embed/blob/d156d86913fe0e107d016c961604e0b592bf7f55/src/lite-yt-embed.css not being loaded.

**Comment by paulirish** [comment]
Hah.. so funny story.

I, like many others, have a tendency to browse reddit in downtime.  Both the desktop web and mobile web clients.

Their mobile web experience is user-hostile and has championed dark patterns that, sadly, other sites have adopted. That's irrelevant to this story, but.. it's true. Anyhow..

Every once in a while, when I click on the play button on a video in the reddit feed, it starts **twice**. You can only see/pause one of them, and the other's audio will keep going.  With enough back/forward/clicks (or a reload) things will stop, but, obviously fairly annoying. I've noticed this happen like 1% of the time for the past 18 months, maybe longer.

Between that bug and noting that sometimes the thumbnail image [looked a little low res](https://github.com/paulirish/lite-youtube-embed/pull/167), I had a sneaking suspicion. 👀  I popped open devtools and, ayup: `<lite-youtube>` in action.

In honesty, I had forgotten completely about this duplicate bug here, fixed by @codepuncher. This was all 3 years ago!  

So yeah, turns out, I'm personally at fault for the bug that was annoying me as a reddit user. :D 

<img width="1634" alt="image" src="https://github.com/user-attachments/assets/79fd31e8-8bbd-48b3-bd15-1f3ad7401283">

Sidenote: if anyone knows a reddit team developer, ask them to upgrade!
