### ISSUE TITLE
Multiple videos won't play at the same time, using open PR #90 for double click on mobile fix

### ISSUE THREAD

**Issue by markovucurovic** [paulirish/lite-youtube-embed#94]
#90

**Comment by Garbee** [comment]
While it is understandable that you’d like to see a fix, there isn’t anything that can be done within this repo until a PR is merged. That is why PRs get reviewed and tested before merge. This is in fact a known issue in that PR discussion.

As it is, there is nothing broken for this situation in the current code here. This is someone else’s modifications that you are choosing to use instead of the stable code that is causing it.

What is the result you’d like to see happen here from this issue?

**Comment by markovucurovic** [comment]
To be able to play multiple videos at the same time and not to have to press twice on mobile for video to start playing

**Comment by philwolstenholme** [comment]
Hi @markovucurovic, as @Garbee has said, you don't need to raise a Github issue about a PR that has not yet merged – you can just leave comments on the PR directly. 

I can see you've already left a comment on #90, so I think you can close this issue. Technically, there's no bug until the PR has actually been merged in, and it most likely won't be merged in until your comment has been addressed.
